name: EcoMythic
version: '${project.version}'
main: me.lojosho.ecomythic.EcoMythic
api-version: 1.18
authors: [ LoJoSho ]
depend:
  - MythicMobs
  - eco
softdepend:
  - EcoItems
  - EcoArmor
  - StatTrackers